// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jedotshnjqnpgiegxcah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImplZG90c2huanFucGdpZWd4Y2FoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNjM0MTMsImV4cCI6MjA2MTkzOTQxM30.1o9i2qT7KJUdXlDP5Yd6Vn_pgNMrwkFOMSG1vr3tFYo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);